name: Laboratorium Technologie chmurowe - Zadanie 1, Dodatek 1 - integracja z GitHub Actions

on:
  push:
    branches: [master]

env:
  # podpunkt 3 - wykorzystujemy rejestr GitHub Container Registry (GHCR)
  REGISTRY: ghcr.io
  IMAGE_NAME: technologie_chmurowe_lab:zad1

jobs:
  build-and-push:
    name: Zbuduj i opublikuj obrazy
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod (checkout)
        uses: actions/checkout@v2

      - name: Skonfiguruj QEMU
        uses: docker/setup-qemu-action@v1

      - name: Skonfiguruj Buildx
        uses: docker/setup-buildx-action@v1

      - name: Zaloguj się do repozytorium
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          # nazwa użytkownika - taka sama jak konto GitHub, na które jesteśmy zalogowani podczas push'a
          username: ${{ github.actor }}
          # GitHub token jako hasło - GitHub automatycznie uwierzytelni się jako nasz użytownik w GitHub Actions
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Zbuduj i opublikuj
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v7, linux/arm64/v8, linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          # podpunkt 2 - cache; używamy GitHub Actions (GHA)
          cache-from: type=gha
          cache-to: type=gha
